'use strict';

const ROLES = Object.freeze({
  USER: 'user',
  ADMIN: 'admin',
});

const DOC_STATUS = Object.freeze({
  UPLOADED: 'uploaded',
  IN_PROGRESS: 'in_progress',
  SIGNED: 'signed',
});

const AUDIT_ACTIONS = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED: 'PASSWORD_RESET_COMPLETED',

  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_VIEWED: 'DOCUMENT_VIEWED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  DOCUMENT_DELETED: 'DOCUMENT_DELETED',
  DOCUMENT_SIGNED: 'DOCUMENT_SIGNED',

  SIGNATURE_CREATED: 'SIGNATURE_CREATED',
  SIGNATURE_DELETED: 'SIGNATURE_DELETED',

  DOCUMENT_VERIFIED: 'DOCUMENT_VERIFIED',

  ADMIN_VIEWED_USERS: 'ADMIN_VIEWED_USERS',
  ADMIN_UPDATED_USER: 'ADMIN_UPDATED_USER',
});

const TARGET_TYPES = Object.freeze({
  USER: 'User',
  DOCUMENT: 'Document',
  SIGNATURE: 'Signature',
});

module.exports = { ROLES, DOC_STATUS, AUDIT_ACTIONS, TARGET_TYPES };
